### ISSUE TITLE
Burn firmware to a blank chip and check validity

### ISSUE THREAD

**Issue by qdot** [metafetish/buttshock-et312-firmware#4]
Have someone with a slotted ET-312 (looking at you, @Orgasmscience) burn the firmware to a blank ATMega16 and get it working in the box.

**Comment by qdot** [comment]
Now that we have the bootloader, done by @kinkyhacks. Works! yay!

**Comment by ds715255** [comment]
I'm trying to burn the firmware on a blank chip. Have to say I want to learn something about that electronics stuff and thought it would be a good idea to try to rebuild (and later improve) the ET312. Found the schematics here and thought .. why not try it ;)

So now I've built up the basic parts (power source, display and buttons). Burned the decrypted firmware and left out the bootloader. But it's basically just resetting itself after a second. Wiring looks okay, as the display shows text with an own program. Read the disassembly but can't figure out what's wrong.

Is there anything I'm missing? Does the firmware image needs some preparation? Some special fuse settings (think I tried them all ^^)? I would be grateful for any hint.

**Comment by qdot** [comment]
@ds715255 Did you see the oscillator calibration value on the chip? The last byte of the flash needs to be set to the 8mhz calibration value for the chip clock, otherwise the chip will have lots of weird issues when it sets the clock up.

I'll try to add instructions on how to do this to the README.

**Comment by ds715255** [comment]
So, got some time to work on the issue. I used hardware debugging to find the issue. Basically it was the power source. The firmware is quite picky about it. I was also missing the output stage which is needed. (I'm not that good with assembler ^^) But so far it boots up, shows the menu and pushs out a signal. However output is by far too weak (even when everything is cranked up). On oscillator the signal looks good. So I assume I got the wrong transformer. Do you have any more specification than 1:4.7? What transformer was meant in the datasheet? I read and tried a lot the last weeks but I'm not getting anywhere. Thanks a lot for your work. And I really don't think this is the right place to ask questions but I have no idea where to do it ;)

**Comment by qdot** [comment]
Here is fine. We've got a schematics repo now too, but eh. I'm not a stickler for issue location.

Anyways, yeah, the transformer has been an issue. The closest one that someone on Telegram found was

http://www.mouser.com/ds/2/449/XC-600127-202003.pdf

Apparently this one is similar to the discontinued one on the boards (this is from a rev. e board, btw). In terms of replicating the output stage, there's also a fetlife thread in relation to the arduino shield project that may be useful:

https://fetlife.com/groups/210/group_posts/9372764

Most of the electronics side of this is still out of my knowledge range, so I'm just repeating what others are telling me. :)

**Comment by qdot** [comment]
Annnnnnnd another thing that came up on telegram:

Are you skipping the FET calibration?  That would cause the same issue because it adds an offset to the DAC output. Try sticking something into $406b and $406c (should be a value around 20ish?)

**Comment by ds715255** [comment]
I skipped the calibration in the first place but now I'm using stock firmware without modification. Will have a few days off so may have some more time to look into the issue (and what I get for $406b/c ^^). Thanks so much for ur help! I appreciate it!
