### ISSUE TITLE
Have firmware always return 0x00 for its side of the encryption key

### ISSUE THREAD

**Issue by qdot** [metafetish/buttshock-et312-firmware#6]
Right now, users can only connect to the ET-312 during the end of the boot sequence. If a key is pressed, serial connections no longer work. Similarly, if serial disconnects, it cannot be reconnected until the box is rebooted.

**Comment by kinkyhacks** [comment]
(You can regain serial and reconnect if you remember the xor key, perhaps updated fw could always pick the same xor key so it works more reliably even with existing sw).

**Comment by qdot** [comment]
Ah, yeah, good point. Only reason I had the idea I did was because box state shouldn't matter against software state, so I would've had the protocol reset and require handshake. But I suppose guaranteed disconnect notification not really a luxury we have with serial anyways.

**Comment by qdot** [comment]
Updated the title to reflect the idea better. :)

**Comment by kinkyhacks** [comment]
On 1.6 fw changing 0x18E0 from 0x24 0xD9 to 0xAA 0x27 [mov r26,0] selects 0.  Confirmed working with existing sw and box linking.

**Comment by qdot** [comment]
Man we really gotta get #18 figured out. :|

**Comment by kinkyhacks** [comment]
$ xxd ../firmware/312-16-decrypted.bin  | sed 's/\(18e0:\) 24d9/\1 aa27/' | xxd -r > new-fw.bin

**Comment by kinkyhacks** [comment]
ok, this should be fixed with buttshock-et312-frankenbutt
